"""empty message

Revision ID: e1198bfffb9a
Revises: 
Create Date: 2020-06-09 23:22:35.730795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1198bfffb9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_data', sa.Column('instanceid', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_flow_data_instanceid'), 'flow_data', ['instanceid'], unique=False)
    op.add_column('locations', sa.Column('dhis2id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_locations_dhis2id'), 'locations', ['dhis2id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_dhis2id'), table_name='locations')
    op.drop_column('locations', 'dhis2id')
    op.drop_index(op.f('ix_flow_data_instanceid'), table_name='flow_data')
    op.drop_column('flow_data', 'instanceid')
    # ### end Alembic commands ###
